### ISSUE TITLE
Crash when removing WelcomeCard

### ISSUE THREAD

**Issue by theblixguy** [dexafree/MaterialList#15]
When I try to remove the welcome card from the top of the adapter, my app crashes:

`java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
            at java.util.ArrayList.get(ArrayList.java:310)
            at com.dexafree.materialList.MaterialListViewAdapter.getItem(MaterialListViewAdapter.java:78)
            at com.dexafree.materialList.view.MaterialListView$1.onDismiss(MaterialListView.java:88)
            at com.dexafree.materialList.controller.SwipeDismissListener$4.onAnimationEnd(SwipeDismissListener.java:311)
            at com.nineoldandroids.animation.ValueAnimator.endAnimation(ValueAnimator.java:1034)
            at com.nineoldandroids.animation.ValueAnimator.access$900(ValueAnimator.java:43)
            at com.nineoldandroids.animation.ValueAnimator$AnimationHandler.handleMessage(ValueAnimator.java:669)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5137)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
            at dalvik.system.NativeStart.main(Native Method)`

How I remove the card:

 `mListView.getMaterialListViewAdapter().remove(wc);
                        mListView.getMaterialListViewAdapter().notifyDataSetChanged();`

**Comment by dexafree** [comment]
Solved in the last version
