### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION:

### ISSUE THREAD

**Issue by technohowl** [dexafree/MaterialList#21]
After upgrading the library to 2.0.0
I am getting multiple dex libraries issue:

	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/nhaarman/listviewanimations/util/Swappable;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
  		at com.android.dx.command.dexer.Main.run(Main.java:246)
  		at com.android.dx.command.dexer.Main.main(Main.java:215)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by technohowl** [comment]
https://github.com/dexafree/MaterialList/issues/20  Manually adding the module in the project solved the issue.

**Comment by PJFonseca** [comment]
Have the same problem.

**Comment by eeandrew** [comment]
Me too. I have the same problem

**Comment by eeandrew** [comment]
@technohowl How to add the module manually?

**Comment by technohowl** [comment]
Download the library and import (materialList) in your project. 

Comment or remove the last line  in build.settings 
apply from: '../maven_push.gradle'

**Comment by FHellmann** [comment]
This also works for me:
```java

    compile ('com.github.dexafree:materiallist:2.0.0') {
        exclude group: 'com.nhaarman.listviewanimations'
    }
```

**Comment by pincopallino93** [comment]
Thank you so much @FHellmann, very useful your solution

**Comment by technohowl** [comment]
Thank you @FHellmann

**Comment by technohowl** [comment]
HI @FHellmann 

I did try your feedback. After adding exclude group I did not find any issue with the build but the code throws NoClassDefFound exception

java.lang.NoClassDefFoundError: com.nhaarman.listviewanimations.appearance.simple.AlphaInAnimationAdapter
            at com.dexafree.materialList.view.MaterialListView.setCardAnimation(MaterialListView.java:116)

Any solution for this??

**Comment by FHellmann** [comment]
@technohowl This was due to the fact, that there were more then one library of the *com.nhaarman.listviewanimations* group imported in gradle. With the *exclude group* you excluded all of these imports. But only one produces the issue.

@dexafree This problem should be solved now.

**Comment by dexafree** [comment]
@FHellmann Thanks :)
