### ISSUE TITLE
Access current data model from within OnButttonPressListener?

### ISSUE THREAD

**Issue by cblock** [dexafree/MaterialList#22]
OnButtonPressListener provides only a reference to TextView textView. So my question ist how to access the current card (and its metadata stored inside it) from within the Listener?
Is it good practice to declare a card instance final in order to access it from within the listener?

Example:
```java
      BasicButtonsCard card = new BasicButtonsCard();
      card.setTitle(dataPojo.getTitle());
      card.setDescription(dataPojo.getSource());
      card.setLeftButtonText("Dislike");
      card.setRightButtonText("Like");
      card.setShowDivider(true);
      card.setDismissible(true);
      card.setOnLeftButtonPressedListener(new OnButtonPressListener() {
        @Override
        public void onButtonPressedListener(TextView textView) {
           //Accessing "card" right here would only be possible if it was declared 'final'
           restClient.postUpdate("Dismiss", card.getTitle()); 
          card.dismiss(); 
        }
      });
      materialListView.add(card);
```
For me it would be great if onButtonPressListener would also provide access to the card like

```java
onButtonPressedListener(TextView textView, Card currentCard)
```

**Comment by cblock** [comment]
One thing I also noticed: If I declare the "card" variable final and then dismiss cards by clicking on the left button, the first card will be dismissed correctly, the click on the left button of the second card actually dismisses the third card and a click on any other card's left button then leads to 
```
    java.lang.RuntimeException: Could not dispatch event: class com.dexafree.materialList.events.DismissEvent to handler [EventHandler public void com.dexafree.materialList.view.MaterialListView.onCardDismiss(com.dexafree.materialList.events.DismissEvent)]: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
            at com.squareup.otto.Bus.throwRuntimeException(Bus.java:456)
            at com.squareup.otto.Bus.dispatch(Bus.java:386)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
            at com.squareup.otto.Bus.post(Bus.java:336)
            at com.dexafree.materialList.events.MainThreadBus.post(MainThreadBus.java:31)
            at com.dexafree.materialList.model.Card.dismiss(Card.java:108)
            at com.blockconsult.nominator.MainActivity$2.onButtonPressedListener(MainActivity.java:95)
            at com.dexafree.materialList.view.BasicButtonsCardItemView$1.onClick(BasicButtonsCardItemView.java:63)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.view.View.getTag()' on a null object reference
            at com.dexafree.materialList.view.MaterialListView.onCardDismiss(MaterialListView.java:160)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
            at com.squareup.otto.Bus.dispatch(Bus.java:384)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
            at com.squareup.otto.Bus.post(Bus.java:336)
            at com.dexafree.materialList.events.MainThreadBus.post(MainThreadBus.java:31)
            at com.dexafree.materialList.model.Card.dismiss(Card.java:108)
            at com.blockconsult.nominator.MainActivity$2.onButtonPressedListener(MainActivity.java:95)
            at com.dexafree.materialList.view.BasicButtonsCardItemView$1.onClick(BasicButtonsCardItemView.java:63)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    ```

**Comment by FHellmann** [comment]
I have added the Card to the OnButtonPressListener. For now you can declare your Card local variable as final to access it from the Listener.

I'm looking forward to fix this Bug as soon as possible.

**Comment by cblock** [comment]
Great, thanks a lot. I just checked out your PR branch and tried it out in my app. 
It works very well for me and also seems to address the runtime error.
