### ISSUE TITLE
Trying to use 2.1.0

### ISSUE THREAD

**Issue by drabelo** [dexafree/MaterialList#40]
Okay I see that you updated it, but none of the sample cards are appearing. In the README you say to import the module samplecards and compile. Where is that? I thought it was supposed to all be included in the library

Thanks!

PS. Really awesome work

**Comment by dexafree** [comment]
My fault, did not update that part of the README.md

You only need to import

```groovy
compile 'com.github.dexafree.materiallist:2.1.0'
```

And the cards will be available

Thus, it looks like I'm still not able to solve the multi-dex issue. Could you please tell me if you are able to compile with it?

Thanks!

**Comment by drabelo** [comment]
Gradle builds fine in Android studio.

When I try to compile and run the app, I get this error


Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Users/dailtonrabelo/Library/Android/sdk/build-tools/19.1.0/dx --dex --no-optimize --output /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/dex/debug /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/classes/debug /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/support-annotations-21.0.3-8c70d15b97e6401804a2375989dda88dd7c0351f.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-cd535e6d9106d950ed80e7b041a9f056918c112d.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-8b22cd651cc6feb083e3a20aa08de8accd4e0b2b.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/lib-core-3.1.0-9d9812b6927b51bc908c5821d04ccdc3a15b1246.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-53bab9ca5d768a1e73433621aa9fb19e71efe9ee.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-9a25cb6052fe7df06598933364aa5c7499898d20.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-5ae34638f09c0e850ee38243287b1ad16f3d1ddf.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/otto-1.3.5-aded976318312cf9f4b70b56985a503b09dac257.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-57beb9d6e6bdaf40ab66a710e1d15a93a85901cf.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-abfea3822edbb9c3ba46260be57d13d2a369357a.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-98af923120e64bd45e89a9259c706d0552872376.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-04f591e8ad214c8f0ea3064c5075ec477c8aaa30.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-c86cc2d76221791e2688bb0e32acdb76c96901d1.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-d6b761055cc1a279696defcea6b953a82f1b0b00.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-c29a8f4b5613db996828a6c4cf9a667cd3844bc8.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/library-2.4.0-57066e18b4e739b62b22a5310bdb08d17f64dcd6.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-d6274194d61cb16f5a7aa4f385f9895ca970bd14.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/internal_impl-21.0.3-b4eb3abfbfba462390efc5d87a8ff71f5272b76d.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-a3083efd88301a1cdea9c831311343fed1450cb3.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-e99f94b887def5003f9668ecff66145fac799f67.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-fe6ad171a14c917709d71312f194573761208500.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/classes-98b5eb9df4d1002a1d051b7b5525af474b8fbecf.jar /Users/dailtonrabelo/AndroidStudioProjects/TMBB/app/build/intermediates/pre-dexed/debug/joda-time-2.3-3e129b3f30e2362a59eba7203e827d6d9cec1669.jar
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexException: Multiple dex files define Lcom/nhaarman/listviewanimations/util/Swappable;
  		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:594)
  		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:552)
  		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:533)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:170)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:439)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:287)
  		at com.android.dx.command.dexer.Main.run(Main.java:230)
  		at com.android.dx.command.dexer.Main.main(Main.java:199)
  		at com.android.dx.command.Main.main(Main.java:103)

**Comment by dexafree** [comment]
Yes, same issue here.

I thought that is was due to having it imported in both core and implementation, but now it's just one module, and it's still crashing :tired_face: 

I'm trying to solve it, but by now, you can just import the library into your project (cloning the repo and copying it).

Sorry for the inconvenience, but believe me, I'm definitely tired of this error and I want to have it fixed ASAP

**Comment by drabelo** [comment]
No errors in Android Studio when compiling.

When I run the app and start the activity that has the materialList, I get this error

01-29 13:53:13.215    9754-9754/com.drabelo.tmbb E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.drabelo.tmbb, PID: 9754
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.drabelo.tmbb/com.example.tmbb.DetailViewActivity}: android.view.InflateException: Binary XML file line #118: Error inflating class com.dexafree.materiallistviewexample.view.MaterialListView
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5105)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #118: Error inflating class com.dexafree.materiallistviewexample.view.MaterialListView
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.example.tmbb.DetailViewFragment.onCreateView(DetailViewFragment.java:66)
            at android.app.Fragment.performCreateView(Fragment.java:1710)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:891)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1063)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1450)
            at android.app.Activity.performStart(Activity.java:5284)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5105)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dexafree.materiallistviewexample.view.MaterialListView" on path: DexPathList[[zip file "/data/app/com.drabelo.tmbb-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.drabelo.tmbb-1, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at android.view.LayoutInflater.createView(LayoutInflater.java:559)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at com.example.tmbb.DetailViewFragment.onCreateView(DetailViewFragment.java:66)
            at android.app.Fragment.performCreateView(Fragment.java:1710)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:891)
            at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1063)
            at android.app.BackStackRecord.run(BackStackRecord.java:684)
            at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1450)
            at android.app.Activity.performStart(Activity.java:5284)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5105)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by dexafree** [comment]
Did you import the library by cloning and adding `compile project`, or by adding

```groovy
compile 'com.github.dexafree.materiallist:2.1.0'
```

?

**Comment by drabelo** [comment]
compile project(':materialList')

**Comment by dexafree** [comment]
Try by running the sample project.

Does it crash?

**Comment by drabelo** [comment]
Finally was able to fix it when I noticed that in your README

<com.dexafree.materiallistviewexample.view.MaterialListView
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:id="@+id/material_listview"/>

You have materialListViewExample and it should just be materialListView.

Thanks!

Now, I'm wondering how to handle onclick listeners? Don't see any options on that.. Is it not possible?

**Comment by dexafree** [comment]
Fixed: https://github.com/dexafree/MaterialList/commit/3740a8cce40b634c6e79d828f4b4dddd2987ed5d

Which OnClickListeners you mean?
OnItemClickListeners?
Or the Text ones?
