### ISSUE TITLE
Exception on rotation

### ISSUE THREAD

**Issue by FHellmann** [dexafree/MaterialList#44]
When I rotate my device I received the following Exception:
```java
Process: de.fh.budgetkeeper.debug, PID: 1353
    java.lang.RuntimeException: Unable to start activity ComponentInfo{de.fh.budgetkeeper.debug/de.fh.budgetkeeper.ui.MainActivity}: java.lang.ClassCastException: android.widget.AbsListView$SavedState cannot be cast to com.etsy.android.grid.StaggeredGridView$GridListSavedState
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3738)
            at android.app.ActivityThread.access$900(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassCastException: android.widget.AbsListView$SavedState cannot be cast to com.etsy.android.grid.StaggeredGridView$GridListSavedState
            at com.etsy.android.grid.StaggeredGridView.onRestoreInstanceState(StaggeredGridView.java:1292)
            at android.view.View.dispatchRestoreInstanceState(View.java:12799)
            at android.view.ViewGroup.dispatchThawSelfOnly(ViewGroup.java:2657)
            at android.widget.AdapterView.dispatchRestoreInstanceState(AdapterView.java:791)
            at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:2643)
            at android.view.View.restoreHierarchyState(View.java:12777)
            at android.support.v4.app.Fragment.restoreViewState(Fragment.java:465)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:969)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
            at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
            at android.app.Activity.performStart(Activity.java:5241)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2168)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3738)
            at android.app.ActivityThread.access$900(ActivityThread.java:135)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
```

It seems to come from the saving of the list (MaterialListView) SavedState which will be given to the grid (MaterialStaggeredGridView) and can not be converted to GridListSavedState....?

**Comment by dexafree** [comment]
Yes, it looks like that it cannot be casted :persevere: 

I don't really know how to address this issue, and in addition, StaggeredGridView does not support single column lists

**Comment by dexafree** [comment]
I have been testing this feature this evening, and I might have found a solution.

It needs testing, but making MaterialListView inherit from StaggeredGridView, like MaterialStaggeredGridView, could solve the problem, as 

```java
setColumnCountPortrait(1);
```

is allowed.

Will update when I have time to test it deeply (this week).

**Comment by FHellmann** [comment]
I also tried this solution with setColumnCountPortrait(1). When I execute the App, also 2 columns appear?
Maybe this is a bug of StaggeredGridView or I did something wrong...

**Comment by FHellmann** [comment]
I'm currently working on an alternative solution for this issue. I try to merge the StaggeredView and normal View together.
When I finished my work and tested it already I will give you a PR. ;)

**Comment by dexafree** [comment]
I tried extending StaggeredGridView and forcing its columns to 1, but then I got some strange behaviours, such as only showing 1 column, but only using half screen

**Comment by dexafree** [comment]
Fixed https://github.com/dexafree/MaterialList/issues/49
