### ISSUE TITLE
Crash when removing card.

### ISSUE THREAD

**Issue by Anatidae-Project** [dexafree/MaterialList#72]
I got a crash when removing a card. Basically, I have a UI that needs only 3 cards on the screen at once. I'd like to use the MaterialList as it follows UI patterns elsewhere. 

The code to remove is pretty straight forward:
```java
scanListView = (MaterialListView) rootView.findViewById(R.id.scan_listview);
if (visibleScans.size() > MAXIMUM_VISIBLE_SCANS) {
    HistoryCard cardToRemove = visibleScans.get(0);
    cardToRemove.setDismissible(true);
    scanListView.remove(cardToRemove);  // Needs dismissible set to true.
    visibleScans.remove(0); // Works properly
}
```

Here is the error:

04-23 11:01:23.289    7063-7063/com.globesherpa.enforcer E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.globesherpa.enforcer, PID: 7063
    java.lang.RuntimeException: Could not dispatch event: class com.dexafree.materialList.events.DismissEvent to handler [EventHandler public void com.dexafree.materialList.view.MaterialListView.onCardDismiss(com.dexafree.materialList.events.DismissEvent)]: Attempt to read from field 'android.view.View android.support.v7.widget.RecyclerView$ViewHolder.itemView' on a null object reference
            at com.squareup.otto.Bus.throwRuntimeException(Bus.java:456)
            at com.squareup.otto.Bus.dispatch(Bus.java:386)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
            at com.squareup.otto.Bus.post(Bus.java:336)
            at com.dexafree.materialList.events.MainThreadBus.post(MainThreadBus.java:31)
            at com.dexafree.materialList.events.BusProvider.dismiss(BusProvider.java:22)
            at com.dexafree.materialList.view.MaterialListView.remove(MaterialListView.java:118)
            at com.globesherpa.enforcer.scanner.ScanFragment.didScanBarcode(ScanFragment.java:169)
            at com.mirasense.scanditsdk.internal.gui.ScanditSDKOverlayView$BarcodeOverlayMessageHandler.handleMessage(ScanditSDKOverlayView.java:564)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5972)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'android.view.View android.support.v7.widget.RecyclerView$ViewHolder.itemView' on a null object reference
            at com.dexafree.materialList.view.MaterialListView.onCardDismiss(MaterialListView.java:171)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
            at com.squareup.otto.Bus.dispatch(Bus.java:384)
            at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:367)
            at com.squareup.otto.Bus.post(Bus.java:336)
            at com.dexafree.materialList.events.MainThreadBus.post(MainThreadBus.java:31)
            at com.dexafree.materialList.events.BusProvider.dismiss(BusProvider.java:22)
            at com.dexafree.materialList.view.MaterialListView.remove(MaterialListView.java:118)
            at com.globesherpa.enforcer.scanner.ScanFragment.didScanBarcode(ScanFragment.java:169)
            at com.mirasense.scanditsdk.internal.gui.ScanditSDKOverlayView$BarcodeOverlayMessageHandler.handleMessage(ScanditSDKOverlayView.java:564)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5972)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by dexafree** [comment]
I suppose that visibleScans is a List of Cards?

I think it might be related to this line:

https://github.com/dexafree/MaterialList/blob/df7b9e8acdf143a67cf2dab319c4da8d4f6ebd1c/materialList/src/main/java/com/dexafree/materialList/view/MaterialListView.java#L170

Could you please elaborate the sample a little bit?
I'd like to reproduce the error and try to see what makes it crash

**Comment by Anatidae-Project** [comment]
Yes. I instance a card and store it in visibleScans. I didn't see a quick api to get a size of cards in the MaterialList.

Basically, in this case, I have my MaterialList that will contain around 3 or 4 cards. The UI is that every new card gets added to the top of the list, pushing the older cards down. Once it hits the maximum, the bottom one gets removed. 

So, when I add a card, I also add it to an ArrayList. I then take the top of that array list and use that stored card reference to call remove. Since posting this issue, I've reversed my ArrayList so that the indexes match what the MaterialList has (same error of course). But that's because the dismiss listener works fine. So on dismiss I use the index value to also remove the reference from my ArrayList.

In an ideal world, I could just have a size() method I could call and then remove(index) so I could remove any card I needed.


This is unrelated, but I was excited to turn on animation:
```java
scanListView.setItemAnimator(new SlideInDownAnimator());
``` 
But that line seems to do nothing. Is that formatting correct here? I'm using the animation libs you recommended from wasabeef.

**Comment by Anatidae-Project** [comment]
To avoid opening up another ticket. Do you also have an example on updating card data?
In specific, I was trying to update the opacity. 

When I change the value nothing happens, but I was assuming I would need to do a notification. Not sure if this pattern is correct:
card.setOpacity(0.75f);
scanListView.getAdapter().notifyDataSetChanged();

**Comment by Anatidae-Project** [comment]
I think it might have been a race condition. I am now adding my new card when OnDismissCallback fires and setting updated card values after that.
